# Tomcat
server:
  tomcat:
    max-threads: 10
    min-spare-threads: 10
  port: 7777

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:rm-bp1t841081e44371olo.mysql.rds.aliyuncs.com}:${MYSQL_PORT:3306}/kwai?useUnicode=true&characterEncoding=UTF8
    username: rmadmin
    password: zpgj@fc2018
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

